// This code is generated by ProgAst on Sat Mar 28 19:11:43 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-802G.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	string Input, Heidi = "heidi";
	int Index = 0;
	cin>>Input;
	for(int i=0; i<Input.size(); i++)
    {
        if(Input[i]==Heidi[Index]) Index++;
        if(Index==5){
            cout<<"YES";
            return 0;
        }
    }
    cout<<"NO";

	return 0;
}
