// This code is generated by ProgAst on Sun Apr 19 20:38:51 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-459B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define FOR(start, end)           for(int i=start; i<end; i++)
#define FORR(start, end)          for(int j=start; j<end; j++)
#define RFOR(start, end)          for(int k=start-1; k>=end; k--)
#define MEM(Name, type)           memset(Name, type, sizeof(Name))
#define lld                       long long int
#define fio                       freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	fio;
	long long int n;
	cin>>n;
    long long int beauty[n];
    for(int i=0; i<n; i++) cin>>beauty[i];
    sort(beauty,beauty+n);
    long long int count_first = 0, count_last = 0, sum;
    long long int maximum = beauty[n-1]-beauty[0];
    for(int i=0; i<n; i++)
    {
        if(beauty[0]==beauty[i]) count_first++;
        if(beauty[n-1]==beauty[i]) count_last++;
    }
    if(count_first==n) sum = count_first*(count_first-1)/2;
    else sum = count_first*count_last;
    cout<<maximum<<" "<<sum<<endl;

	return 0;
}
