// This code is generated by ProgAst on Wed Apr 15 20:16:42 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-721B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    fio;
    int n,k,a[101],x1,x2;
    string s;
    cin>>n>>k;
    for(int i=1; i<=n; i++)
    {
        cin>>s;
        a[i]=s.length();
    }
    sort(a+1,a+n+1);
    cin>>s;
    a[0]=s.length();

    for(int i=1; i<=n; i++)
        if(a[i]==a[0])
        {
            x1=i;
            break;
        }

    for(int i=n; i>=1; i--)
        if(a[i]==a[0])
        {
            x2=i;
            break;
        }

    cout<<x1+((x1-1)/k)*5<<" "<<x2+((x2-1)/k)*5;

    return 0;
}
