// This code is generated by ProgAst on Wed Mar 25 11:23:35 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1296B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    //fio;
    int test;
    cin>>test;
    long long int burles, spent,cashback;
    while(test--)
    {
        cin>>burles;
        spent = 0 ;
        while ( burles >= 10 )
        {
            cashback = burles / 10 ;
            spent = spent + ( cashback * 10 ) ;
            burles = burles + cashback - ( cashback * 10 ) ;
        }
        cout << spent + burles << endl;
    }

    return 0;
}
