// This code is generated by ProgAst on Wed Apr 08 00:01:06 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-476A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    int Stairis, Integer;
    cin>>Stairis>>Integer;
    if(Stairis<Integer)
        cout<<"-1";
    else
    {
        int Ans = (Stairis+(2*Integer)-1)/2/Integer*Integer;
        cout<<Ans;
    }
    return 0;
}
