// This code is generated by ProgAst on Mon Apr 27 20:27:15 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-868A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define FOR(start, end)           for(int i=start; i<end; i++)
#define FORR(start, end)          for(int j=start; j<end; j++)
#define RFOR(start, end)          for(int k=start-1; k>=end; k--)
#define MEM(Name, type)           memset(Name, type, sizeof(Name))
#define lld                       long long int
#define fio                       freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	string pass, inp;
	bool flag1 = false, flag2 = false;
	int n;
	cin>>pass>>n;
	while(n--)
    {
        cin>>inp;
        if(inp==pass) flag1 = true, flag2 = true;
        if(inp[0]==pass[1]) flag1 = true;
        if(inp[1]==pass[0]) flag2 = true;
        if(flag1 && flag2)
        {
            cout<<"YES"<<endl;
            return 0;
        }
    }
	cout<<"NO"<<endl;
	return 0;
}
