// This code is generated by ProgAst on Tue Mar 24 21:50:51 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1189A.cpp
// Problem Link:

// © Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    //fio;
    string s;
    int n;
    cin>>n>>s;

    int x=0;
    for(int i=0; i<n; i++)
        if(s[i]=='1')
            x++;
    if(x+x==n)
    {
        cout<<2<<endl;
        cout << s.substr(0,n-1) << " "<<s[n-1]<<endl;
    }
    else
    {
        cout<<1<<endl;
        cout<<s<<endl;
    }

    return 0;
}
