// This code is generated by ProgAst on Sun Apr 19 20:17:03 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1256A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define FOR(start, end)           for(int i=start; i<end; i++)
#define FORR(start, end)          for(int j=start; j<end; j++)
#define RFOR(start, end)          for(int k=start-1; k>=end; k--)
#define MEM(Name, type)           memset(Name, type, sizeof(Name))
#define lld                       long long int
#define fio                       freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	fio;
	int test;
	cin>>test;
	while(test--)
    {
        lld a, b, n, s;
        cin>>a>>b>>n>>s;
        bool flag = false;
        if(a*n+b>=s)
        {
            if(a*n<=s) flag = true;
            else
            {
                s = s%n;
                if(s<=b) flag = true;
            }
        }
        if(flag==true)
            cout<<"Yes"<<endl;
        else
            cout<<"No"<<endl;
    }

	return 0;
}
