// This code is generated by ProgAst on Sat Apr 11 11:17:54 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1334C.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    long long int test,monster;
    cin>>test;
    while(test--)
    {
        cin>>monster;
        long long int ans = 0, mm = LLONG_MAX, x;
        vector<long long int> a(monster), b(monster);
        for(long long int i=0; i<monster; i++)
        {
            cin>>a[i]>>b[i];
        }
        for(long long int i=0; i<monster; i++)
        {
            x = max(0LL,a[i]-b[(i+monster-1)%monster]);
            ans += x;
            a[i] -= x;
            mm = min(mm,a[i]);
        }
        cout<<ans+mm<<endl;
    }

    return 0;
}
