// This code is generated by ProgAst on Sat Mar 28 19:26:34 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1257B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    fio;
    int Test;
    cin>>Test;
    while(Test--)
    {
        long long int X, Y;
        cin>>X>>Y;
        if(X==1)
        {
            if(Y==1)
                cout<<"YES"<<endl;
            else
                cout<<"NO"<<endl;
        }
        else if(X==2 || X==3)
        {
            if(Y<4) cout<<"YES"<<endl;
            else cout<<"NO"<<endl;
        }
        else cout<<"YES"<<endl;
    }

    return 0;
}
