// This code is generated by ProgAst on Fri Mar 27 23:39:31 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1008B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    int N;
    cin>>N;
    long long int Data[N][2], A, B, M;
    for(int i=0; i<N; i++)
    {
        cin>>A>>B;
        if(max(A,B)<=M) M = max(A,B);
        else if(min(A,B)<=M) M = min(A, B);
        else{
            cout<<"NO";
            return 0;
        }
    }
    cout<<"YES";
    return 0;
}
