// This code is generated by ProgAst on Fri Apr 17 21:29:07 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1037C.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define FOR(start, end)           for(int i=start; i<end; i++)
#define FORR(start, end)          for(int j=start; j<end; j++)
#define RFOR(start, end)          for(int k=start-1; k>=end; k--)
#define MEM(Name, type)           memset(Name, type, sizeof(Name))
#define lld                       long long int
#define fio                       freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    int len;
    cin>>len;
    string st1, st2;
    cin>>st1>>st2;
    int cnt = 0;
    for(int i=0; i<len; i++)
    {
        if(st1[i]!=st2[i])
        {
            cnt++;
            if(st1[i+1]==st2[i]&&st1[i]==st2[i+1])
                swap(st1[i],st1[i+1]);
        }
    }
    cout<<cnt;
    return 0;
}
