// This code is generated by ProgAst on Sat Mar 28 19:02:52 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1293B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);
double sum(int n)
{
    double i, s = 0.0;
    for (i = 1; i <= n; i++)
        s = s + 1/i;
    return s;
}

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    int Opponents;
    cin>>Opponents;
    printf("%0.12lf",sum(Opponents));

    return 0;
}
