// This code is generated by ProgAst on Sun Mar 29 13:24:31 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-447B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	string String;
	int N;
	int Values[256], Max = 0, Ans = 0;
	cin>>String>>N;
	for(int i=97; i<123; i++){
        cin>>Values[i];
        Max = max(Max, Values[i]);
	}
	//cout<<"Max "<<Max<<endl;
	for(int i=0; i<String.size(); i++)
    {
        Ans = Ans + (i+1)*Values[String[i]];
    }
    for(int i=String.size(); i<N+String.size(); i++)
    {
        Ans = Ans + (i+1)*Max;
    }
    cout<<Ans;

	return 0;
}
