// This code is generated by ProgAst on Fri Mar 27 22:52:45 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1189B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	fio;
	long long int N,;
	cin>>N;
	long long int Integers[N];
	for(long long int i=0; i<N; i++) cin>>Integers[i];
	sort(Integers, Integers+N);
    if(Integers[n-1]<Integers[n-2]+Integers[n-3]){

    }

	return 0;
}
