// This code is generated by ProgAst on Wed Mar 25 17:46:11 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-977B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    //fio;
    int Length, Maximum = 0, Flag, Count = 0;
    string String;
    cin>>Length>>String;
    for(int i=0; i<Length; i++)
    {
        Count = 0;
        for(int j=0; j<Length-1; j++)
        {
            if(String[i]==String[j] && String[i+1]==String[j+1])
            {
                Count++;
            }
        }
        if(Count>Maximum)
        {
            Maximum = Count;
            Flag = i;
        }
    }
    cout<<String[Flag]<<String[Flag+1];
    return 0;
}
