// This code is generated by ProgAst on Wed Mar 25 10:56:22 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-672B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	//fio;
	int length, count = 0;
	string word;
	int counter[150] = {0};
	cin>>length>>word;
	if(length==1) cout<<0;
	else if(length>26) cout<<"-1";
	else{
        for(int i=0; i<length; i++) counter[word[i]]++;
        for(int i=97;i<123;i++){
            if(counter[i]>1) count = count + (counter[i] - 1);
        }
        if(count==0) cout<<"0";
        else cout<<count;
	}

	return 0;
}
