// This code is generated by ProgAst on Mon Mar 23 20:15:11 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-465A.cpp
// Problem Link: https://codeforces.com/contest/465/problem/A

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	//fio;
	long long int n, count=0;
	string pre;
	cin>>n>>pre;
	for(int i=0; i<n; i++)
    {
        if(pre[i]=='1'){
            count++;
        }
        else{
            count++;
            break;
        }
    }
    cout<<count;
	return 0;
}
