// This code is generated by ProgAst on Wed Mar 25 11:47:11 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1006A.cpp
// Problem Link:
// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	//fio;
	int Length;
	long long int Maximum = 0, Minimum = 0;
	cin>>Length;
	long long int Sequence[Length];
	for(int i=0; i<Length; i++)
    {
        cin>>Sequence[i];
        //Maximum = max(Maximum,Sequence[i]);
        //Minimum = min(Minimum,Sequence[i]);
    }

    for(int i=0; i<Length; i++)
    {
        if(Sequence[i]%2==0) cout<<Sequence[i]-1<<" ";
        else cout<<Sequence[i]<<" ";
    }

	return 0;
}
