// This code is generated by ProgAst on Fri Mar 27 20:37:07 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-486A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    long long int Number;
    cin>>Number;
    if(Number%2!=0) cout<<-(Number+1)/2;
    else cout<<Number/2;

    return 0;
}
