// This code is generated by ProgAst on Sun Apr 19 23:12:19 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1140B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define FOR(start, end)           for(int i=start; i<end; i++)
#define FORR(start, end)          for(int j=start; j<end; j++)
#define RFOR(start, end)          for(int k=start-1; k>=end; k--)
#define MEM(Name, type)           memset(Name, type, sizeof(Name))
#define lld                       long long int
#define fio                       freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    int t, n;
    string s;
    cin >> t;
    for(int tc = 0; tc < t; ++tc)
    {
        cin >> n >> s;
        int res = n - 1;
        for(int i = 0; i < n; ++i)
            if(s[i] == '>' || s[n - 1 - i] == '<')
                res = min(res, i);

        cout << res << endl;
    }

    return 0;
}
