// This code is generated by ProgAst on Sun Apr 19 22:30:17 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-90B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define FOR(start, end)           for(int i=start; i<end; i++)
#define FORR(start, end)          for(int j=start; j<end; j++)
#define RFOR(start, end)          for(int k=start-1; k>=end; k--)
#define MEM(Name, type)           memset(Name, type, sizeof(Name))
#define lld                       long long int
#define fio                       freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    int row, coll;
    cin>>row>>coll;
    string encode[row];
    for(int i=0; i<row; i++)
        cin>>encode[i];
    for(int i=0; i<row; i++)
    {

        for(int j=0; j<coll; j++)
        {
            bool flag = true;
            int count1 = 0;
            for(int m=0; m<coll; m++)
            {

                if(encode[i][j]==encode[i][m])
                {
                    count1++;
                        if(count1==2)
                        {
                            flag = false;
                            break;
                        }
                }
            }
            if(flag)
            {
                int count = 0;
                for(int m=0; m<row; m++)
                {
                    if(encode[i][j]==encode[m][j])
                    {
                        count++;
                        if(count==2)
                        {
                            flag = false;
                        }
                    }
                    if(flag==false) break;
                }
            }
            if(flag) cout<<encode[i][j];
        }

    }
    return 0;
}
