// This code is generated by ProgAst on Sat Mar 28 10:56:49 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-456A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    int N;
    bool Flag = false;
    cin>>N;
    int Price, Quality;
    for(int i=0; i<N; i++)
        {
            cin>>Price>>Quality;
            if(Quality>Price) Flag = true;
        }
    if(Flag) cout<<"Happy Alex"<<endl;
    else cout<<"Poor Alex"<<endl;

    return 0;
}
