// This code is generated by ProgAst on Fri Apr 10 23:13:16 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-270A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	int test;
	cin>>test;
	while(test--)
    {
        int angel;
        cin>>angel;
        if(360%(180-angel)==0) cout<<"YES"<<endl;
        else cout<<"NO"<<endl;
    }

	return 0;
}
