// This code is generated by ProgAst on Mon Mar 30 11:59:00 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-368B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    fio;
    set<int>Array;
    int N, M, X;
    cin>>N>>M;
    int Input[N];
    int Ans[N];
    for(int i=0; i<N; i++) cin>>Input[i];
    for(int i=N-1; i>=0; i--)
    {
        Array.insert(Input[i]);
        Ans[i] = Array.size();
    }
    while(M--)
    {
        cin>>X;
        cout<<Ans[X-1]<<endl;
    }

    return 0;
}
