// This code is generated by ProgAst on Sun Mar 29 22:38:18 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-534A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    int N;
    cin>>N;
    int SeatPlan[N];
    if(N==1 || N==2)
        cout<<1<<endl<<1;
    else if(N==3)
        cout<<2<<endl<<"1 3";
    else if(N==4)
        cout<<4<<endl<<"3 1 4 2";
    else
    {
        cout<<N<<endl;
        if(N%2==0)
        {
            for(int i=0, j=1; i<N/2; i++, j+=2)
                SeatPlan[i] = j;
            for(int i=N/2, j=2; i<N; i++, j+=2)
                SeatPlan[i] = j;
        }
        else
        {
            for(int i=0, j=1; i<=N/2; i++, j+=2)
                SeatPlan[i] = j;
            for(int i=N/2+1, j=2; i<N; i++, j+=2)
                SeatPlan[i] = j;
        }

        for(int i=0; i<N; i++)
            cout<<SeatPlan[i]<<" ";
    }

    return 0;
}
