// This code is generated by ProgAst on Thu Apr 09 23:37:59 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1101A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	int test;
	cin>>test;
	while(test--)
    {
        long long int left, right, divisor;
        cin>>left>>right>>divisor;
        if(left>divisor || right<divisor) cout<<divisor<<endl;
        else{
            cout<<(right/divisor)*divisor+divisor<<endl;
        }
    }

	return 0;
}
