// This code is generated by ProgAst on Fri Mar 27 21:18:49 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1243B1.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    fio;
    int Test;
    cin>>Test;
    while(Test--)
    {
        int N;
        string First, Second;
        cin>>N>>First>>Second;
        int Count=0, Index[N];
        for(int i=0; i<N; i++)
        {
            if(First[i]!=Second[i])
            {
                Index[Count] = i;
                Count++;
            }
        }
        if(Count>2 || Count==1)
            cout<<"No"<<endl;
        else
        {
            if(First[Index[0]]==First[Index[1]] && Second[Index[0]]==Second[Index[1]])
                cout<<"Yes"<<endl;
            else
                cout<<"No"<<endl;
        }
    }

    return 0;
}
