// This code is generated by ProgAst on Tue Apr 07 22:31:19 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-69A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	int N, x, y, z, Sx = 0, Sy = 0, Sz = 0;
	cin>>N;
	for(int i=0; i<N; i++)
    {
        cin>>x>>y>>z;
        Sx += x;
        Sy += y;
        Sz += z;
    }
	if(Sx==0 && Sy==0 && Sz==0) cout<<"YES";
	else cout<<"NO";
	return 0;
}
