// This code is generated by ProgAst on Wed Apr 08 20:01:54 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-712B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
//	fio;
    string Command;
    cin>>Command;
    int X = 0, Y = 0;
    int Length = Command.length();
    if(Length%2==1)
        cout<<-1;
    else
    {
        for(int i=0; i<Length; i++)
        {
            if(Command[i]=='L')
                X--;
            else if(Command[i]=='R')
                X++;
            else if(Command[i]=='U')
                Y++;
            else if(Command[i]=='D')
                Y--;
        }
        int Ans = (abs(X)+abs(Y))/2;
        cout<<Ans;
    }


    return 0;
}
