// This code is generated by ProgAst on Wed Apr 15 19:23:40 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-508B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
#include<string.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	string input, temp;
	cin>>input;
	temp = input;
	int length = temp.size();
	int maximum = 0;
	int index;
	bool flag = false;
	for(int i=0; i<length; i++)
    {
        if((input[i]-'0')%2==0 && (input[i]-'0')<(input[length-1]-'0'))
        {
            swap(input[i],input[length-1]);
            cout<<input;
            return 0;
        }
        else if((input[i]-'0')%2==0 && (input[i]-'0')>(input[length-1]-'0'))
        {
            index = i;
            flag = true;
        }
    }
    if(flag)
    {
        swap(input[length-1],input[index]);
        cout<<input<<endl;
        return 0;
    }
    cout<<-1;

	return 0;
}
