// This code is generated by ProgAst on Sat Mar 28 19:35:49 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1182A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	int N;
	cin>>N;
	if(N%2==1) cout<<0;
	else
	{
	    long long int Ans = pow(2,N/2);
        cout<<Ans;
	}
	return 0;
}
