// This code is generated by ProgAst on Wed Mar 25 18:33:51 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1324B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    fio;
    int TestCase, Length;
    cin>>TestCase;
    while(TestCase--)
    {
        bool Flag = false;
        cin>>Length;
        int InputArray[Length];
        for(int i=0; i<Length; i++)
            cin>>InputArray[i];
        for(int i=0; i<Length-1; i++)
        {
            for(int j=i+2; j<Length; j++)
            {
                if(InputArray[i]==InputArray[j])
                {
                    Flag = true;
                    break;
                }
            }
            if(Flag) break;
        }
        if(Flag)
            cout<<"YES"<<endl;
        else
            cout<<"NO"<<endl;
    }

    return 0;
}
