// This code is generated by ProgAst on Tue Apr 14 20:20:41 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-550A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	string main_string;
	cin>>main_string;
	bool found_ab = false, found_ba = false;
	int i;
	for(i=0; i<main_string.size()-1; i++)
    {
        //cout<<"IN Loop"<<endl;
        if(main_string[i]=='A' && main_string[i+1]=='B')
        {
            found_ab = true;
            break;
        }
    }
    i = i + 2;
    //cout<<"i "<<i<<endl;
    for(i; i<main_string.size()-1; i++)
    {
        //cout<<"IN Loop"<<endl;
        if(main_string[i]=='B' && main_string[i+1]=='A')
        {
            found_ba = true;
            break;
        }
    }
    //cout<<"1st "<<found_ab<<" "<<found_ba<<endl;
	if(found_ab == true && found_ba == true)
    {
        cout<<"YES"<<endl;
        return 0;
    }
    found_ab = false, found_ba = false;
    for(i=0; i<main_string.size()-1; i++)
    {
        //cout<<"IN Loop"<<endl;
        if(main_string[i]=='B' && main_string[i+1]=='A')
        {
            found_ba = true;
            break;
        }
    }
    i = i + 2;
    for(i; i<main_string.size()-1; i++)
    {
        //cout<<"IN Loop"<<endl;
        if(main_string[i]=='A' && main_string[i+1]=='B')
        {
            found_ab = true;
            break;
        }
    }
    //cout<<"1st "<<found_ab<<" "<<found_ba<<endl;
    if(found_ab == true && found_ba == true)
    {
        cout<<"YES"<<endl;
        return 0;
    }
    cout<<"NO"<<endl;
	return 0;
}
