// This code is generated by ProgAst on Tue Apr 07 23:41:29 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-82A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    long long int N;

    string Names[]= { "Sheldon", "Leonard", "Penny", "Rajesh", "Howard"};
    cin>>N;
    while(N>5)
        N = (N / 2) - 2;

    cout<<Names[N-1];

    return 0;
}
