// This code is generated by ProgAst on Sun Mar 22 22:18:35 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1300A.cpp
// Problem Link: https://codeforces.com/problemset/problem/1300/A

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	fio;
	int t, n;
	cin>>t;
	while(t--)
	{
	    int sum = 0, count0 = 0, ans;
	    cin>>n;
	    int arr[n];
	    for(int i=0; i<n; i++)
        {
            cin>>arr[i];
            sum += arr[i];
            if(arr[i]==0) count0++;
        }
        sum = sum + count0;

        if(sum==0) ans = count0 + 1;
        else ans = count0;
        cout<<ans<<endl;
	}
	return 0;
}
