// This code is generated by ProgAst on Sun Mar 29 12:57:41 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1213B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	int Test;
	cin>>Test;
	while(Test--)
    {
        int Length, Ans = 0;
        cin>>Length;
        int Prices[Length];
        for(int i=0; i<Length; i++) cin>>Prices[i];
        int Min = Prices[Length-1];
        for(int i=Length-1; i>=0; i--)
        {
            if(Min<Prices[i]) Ans++;
            else Min = min(Min, Prices[i]);
        }
        cout<<Ans<<endl;
    }

	return 0;
}
