// This code is generated by ProgAst on Sun Apr 12 20:31:49 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1339A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	int test;
	cin>>test;
	while(test--)
    {
        long long int n;
        cin>>n;
        cout<<n<<endl;
    }

	return 0;
}
