// This code is generated by ProgAst on Tue Apr 07 22:18:25 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-96A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	string CrtSituation;
	int Count0 = 0, Count1 = 0;
	cin>>CrtSituation;
	for(int i=1; i<CrtSituation.size(); i++)
    {
        if(CrtSituation[i-1]=='0' && CrtSituation[i]=='0') Count0++;
        else if(CrtSituation[i-1]=='0' && CrtSituation[i]!='0') Count0 = 0;
        else if(CrtSituation[i-1]=='1' && CrtSituation[i]=='1') Count1++;
        else if(CrtSituation[i-1]=='1' && CrtSituation[i]!='1') Count1 = 0;

        if(Count0+1==7) {cout<<"YES"; return 0;}
        if(Count1+1==7) {cout<<"YES"; return 0;}
    }

	cout<<"NO";
	return 0;
}
