// This code is generated by ProgAst on Sun Mar 29 15:16:32 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1005B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    string First, Second;
    cin>>First>>Second;
    int LF = First.size(), SF = Second.size(), Count = 0;
    //cout<<"LF SF "<<LF<<" "<<SF<<endl;
    if(LF<SF)
    {
        for(int i = LF-1, j = SF-1; i>=0; i--,j--)
        {
            if(First[i]==Second[j])
                Count++;
            else
                break;
        }
    }
    else
    {
        for(int i = LF-1, j = SF-1; j>=0; i--,j--)
        {
            if(First[i]==Second[j])
                Count++;
            else
                break;
        }
    }

    int Ans = (LF-Count)+(SF-Count);
    cout<<Ans;

    return 0;
}
