// This code is generated by ProgAst on Mon Apr 13 20:23:27 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-519C.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    int expert, nowbie, differ, minimum, reslut, sum = 0;
    cin >> expert >> nowbie;
    differ = abs(expert-nowbie);
    minimum = min(expert,min(nowbie,differ));
    if(minimum == differ)
    {
        reslut = differ;
        sum = expert + nowbie-3*differ;
        reslut = reslut + sum/3;
    }
    else
    {
        reslut = minimum;
    }
    cout << reslut <<endl;

    return 0;
}
