// This code is generated by ProgAst on Fri Mar 27 11:53:39 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1130A.cpp
// Problem Link:
// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    //ios_base::sync_with_stdio(false);
    //cin.tie(null);
    //fio;
    int Length, CountP = 0, CountN = 0;
    cin>>Length;
    int Integers[Length];
    for(int i=0; i<Length; i++)
    {
        cin>>Integers[i];
        if(Integers[i]>0) CountP++;
        else if(Integers[i]<0) CountN++;
    }
    int Half = (Length%2)+(Length/2);
    if(Half>CountP && Half>CountN)
        cout<<0;
    else
    {
        if(CountP>=CountN) cout<<1;
        else cout<<-1;
    }
    return 0;
}
