// This code is generated by ProgAst on Mon Mar 30 11:30:47 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-339B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	long long int N, M, Pos = 1, Ans = 0;
	cin>>N>>M;
	long long int Places[M];
	for(long long int i=0; i<M; i++)
    {
        cin>>Places[i];
        if(Pos <= Places[i]) Ans = Ans + Places[i] - Pos;
        else Ans = Ans + N - Pos + Places[i];
        Pos = Places[i];
    }
	cout<<Ans;
	return 0;
}
