// This code is generated by ProgAst on Sun Mar 22 20:03:18 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1272A.cpp
// Problem Link: https://codeforces.com/contest/1272/problem/A

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	fio;

	int t;
	long long int arr[3];
	long long int ba, cb, ca;
	cin>>t;
	while(t--)
    {
        cin>>arr[0]>>arr[1]>>arr[2];
        sort(arr,arr+3);
        arr[0] += 1;
        arr[2] -= 1;
        ba = arr[1] - arr[0];
        cb = arr[2] - arr[1];
        ca = arr[2] - arr[0];
        if(ba+cb+ca<=0) cout<<0<<endl;
        else cout<<ba+cb+ca<<endl;
    }

	return 0;
}
