// This code is generated by ProgAst on Mon Apr 20 19:20:27 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1066B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define FOR(start, end)           for(int i=start; i<end; i++)
#define FORR(start, end)          for(int j=start; j<end; j++)
#define RFOR(start, end)          for(int k=start-1; k>=end; k--)
#define MEM(Name, type)           memset(Name, type, sizeof(Name))
#define lld                       long long int
#define fio                       freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    int a,r;
    cin>>a>>r;
    int board[a];
    for(int i=0; i<a; i++)
        cin>>board[i];
    int c=0;
    r--;
    for(int i=0; i<a;)
    {
        int pos=-1;
        for(int p=min(a,i+r); p>=max(0,i-r); p--)
        {
            if(board[p]==1)
            {
                pos=p;
                break;
            }
        }
        if(pos==-1)
        {
            cout<<-1<<endl;
            return 0;
        }
        c++;
        i=pos+r+1;
    }
    cout<<c<<endl;
    return 0;
}
