// This code is generated by ProgAst on Sat Apr 11 11:33:44 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1064B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    long long i = 2, n, ans = 2;
    cin>>n;
    if (n==1)
    {
        cout<<1;
        return 0;
    }
    while (i*i<n)
    {
        if(n%i==0)
        {
            ans+=2;
            i++;
        }
        else
            i++;
    }

    if (i*i==n)
        ans++;

    cout<<ans;

    return 0;
}
