// This code is generated by ProgAst on Mon Apr 13 21:44:48 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1335B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	fio;
	int test;
	cin>>test;
	while(test--)
    {
        int n, a, b;
        cin>>n>>a>>b;
        char charc[b];
        for(int i=0, j=97; i<b; i++, j++) charc[i] = j;
        for(int i=0, j=0; i<n; i++)
        {
            cout<<charc[j];
            j++;
            if(j==b) j = 0;
        }
        cout<<endl;
    }

	return 0;
}
