// This code is generated by ProgAst on Mon Mar 23 20:54:08 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1327A.cpp
// Problem Link: https://codeforces.com/contest/1327/problem/A

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    //ios_base::sync_with_stdio(false);
    //fio;
    int t;
    cin>>t;
    while(t--)
    {
        long long int a, b;
        cin>>a>>b;
        if(a==1 && b==1)
            cout<<"YES"<<endl;
        else if(a<=b)
            cout<<"NO"<<endl;
        else
        {
            if(a%2==0 && b%2!=0)
                cout<<"NO"<<endl;
            else if(a%2!=0 && b%2==0)
                cout<<"NO"<<endl;
            else
                cout<<"YES"<<endl;
        }

    }

    return 0;
}
