// This code is generated by ProgAst on Tue Mar 24 19:36:30 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1230B.cpp
// Problem Link:

// Author © Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    //fio;
    int digit, changeable, count = 0;
    cin>>digit>>changeable;
    string number;
    cin>>number;
    if(changeable==0)
        cout<<number;
    else if (digit==1)
        cout<<0;
    else
    {
        if(number[0]=='1')
        {
            for(int i=1; i<digit; i++)
            {
                if(number[i]!='0' && changeable>0)
                {
                    number[i] = '0';
                    changeable--;
                }
            }
        }
        else
        {
            number[0]='1';
            changeable--;
            for(int i=1; i<digit; i++)
            {
                if(number[i]!='0' && changeable>0)
                {
                    number[i] = '0';
                    changeable--;
                }
            }
        }
        cout<<number;

    }

    return 0;
}
