// This code is generated by ProgAst on Thu Apr 16 21:57:10 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-4C.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define FOR(start, end)           for(int i=start; i<end; i++)
#define FORR(start, end)          for(int j=start; j<end; j++)
#define RFOR(start, end)          for(int k=start-1; k>=end; k--)
#define MEM(Name, type)           memset(Name, type, sizeof(Name))
#define lld                       long long int
#define fio                       freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	fio;
	int number;
	cin>>number;
	string request[number];
	int counter[number] = {0};
	for(int i=0; i<number; i++) cin>>request[i];
	for(int i=0; i<number-1; i++)
    {
        if(counter[i]==0)
        {
            int cnt = 0;
            for(int j=i+1; j<number; j++)
            {
                if(request[j]==request[i])
                {
                    cnt++;
                    counter[j] = cnt;
                }
            }
        }
    }

	for(int i=0; i<number; i++)
	{
	    if(counter[i]==0) cout<<"OK"<<endl;
        else cout<<request[i]<<counter[i]<<endl;
	}

	return 0;
}
