// This code is generated by ProgAst on Sun Apr 19 19:31:47 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-349A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define FOR(start, end)           for(int i=start; i<end; i++)
#define FORR(start, end)          for(int j=start; j<end; j++)
#define RFOR(start, end)          for(int k=start-1; k>=end; k--)
#define MEM(Name, type)           memset(Name, type, sizeof(Name))
#define lld                       long long int
#define fio                       freopen("input.txt","r",stdin);


int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	fio;
	int number;
	int count25 = 0, count50 = 0;
	cin>>number;
	int bill;
	for(int i=0; i<number; i++)
    {
        cin>>bill;
        if(bill==25)
        {
            count25++;
        }
        else if(bill==50)
        {
            if(count25<1)
            {
                cout<<"NO"<<endl;
                return 0;
            }
            count25--;
            count50++;
        }
        else if(bill==100)
        {
            if((count25>=1 && count50>=1) || count25>=3)
            {
                if(count25>=1 && count50>=1)
                {
                    count25--;
                    count50--;
                }
                else if(count50<1 && count25>=3)
                {
                    count25 -= 3;
                }
            }
            else
            {
                cout<<"NO"<<endl;
                return 0;
            }
        }
    }
	cout<<"YES"<<endl;
	return 0;
}
