// This code is generated by ProgAst on Sun Mar 29 18:15:01 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1106C.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	long long int N;
	cin>>N;
	long long int Numbers[N];
	for(long long int i=0; i<N; i++) cin>>Numbers[i];
	sort(Numbers,Numbers+N);
	long long int Ans = 0;
	for(int i=0, j=N-1; i<N/2; i++, j--)
    {
        Ans = Ans + (Numbers[i]+Numbers[j])*(Numbers[i]+Numbers[j]);
    }
    cout<<Ans;
	return 0;
}
