// This code is generated by ProgAst on Tue Apr 07 23:48:11 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-577A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	long long int N, K, Count = 0;
	cin>>N>>K;
	for(long long int i=1; i<=N; i++)
    {
       if(K%i==0 && K/i<=N) Count++;
    }
	cout<<Count;
	return 0;
}
