// This code is generated by ProgAst on Fri Apr 10 20:06:58 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1214A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	int total, dollar, euro, ans;
	cin>>total>>dollar>>euro;
	ans = total;
	for(int i=0; (i*5*euro)<=total; i++)
    {
        ans = min(ans,(total-(i*5*euro))%dollar);
    }
    cout<<ans<<endl;

	return 0;
}
