// This code is generated by ProgAst on Sun Apr 19 21:15:55 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-598A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define FOR(start, end)           for(int i=start; i<end; i++)
#define FORR(start, end)          for(int j=start; j<end; j++)
#define RFOR(start, end)          for(int k=start-1; k>=end; k--)
#define MEM(Name, type)           memset(Name, type, sizeof(Name))
#define lld                       long long int
#define fio                       freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    fio;
    int test;
    cin>>test;
    while(test--)
    {
        long long int n, ans, temp = 0;
        cin>>n;
        ans = n*(n+1)/2;
        for(int i=1; i<=n; i*=2)
            temp += i*2;
        cout<<ans-temp<<endl;
    }

    return 0;
}
