// This code is generated by ProgAst on Fri Mar 27 10:38:48 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1328B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    int Test;
    cin>>Test;
    while(Test--)
    {
        int Length, Position;
        bool Flag = false;
        cin>>Length>>Position;
        string Word(Length, 'a');
        //for(int i=0; i<Length; i++) Word[i] = 'a';
        //cout<<"Word"<<Word<<endl;
        for(int i=Length-2; i>=0; i--)
        {
            if(Position <= Length-1-i)
            {
                Word[i] = 'b';
                Word[Length-Position] = 'b';
                Flag = true;
            }
            Position = Position - (Length-1-i);
            if(Flag)
                break;
        }
        cout<<Word<<endl;
    }

    return 0;
}
