// This code is generated by ProgAst on Wed Mar 25 18:20:25 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1325B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    fio;
    int Testcase, Length, Element;
    cin>>Testcase;
    while(Testcase--)
    {
        cin>>Length;
        set<long long int>InputArrey;
        for(int i=0; i<Length; i++)
        {
            cin>>Element;
            InputArrey.insert(Element);
        }
        cout<<InputArrey.size()<<endl;
    }

    return 0;
}
