// This code is generated by ProgAst on Fri Apr 17 20:13:32 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1187B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define FOR(start, end)           for(int i=start; i<end; i++)
#define FORR(start, end)          for(int j=start; j<end; j++)
#define RFOR(start, end)          for(int k=start-1; k>=end; k--)
#define MEM(Name, type)           memset(Name, type, sizeof(Name))
#define lld                       long long int
#define fio                       freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	fio;
	lld length;
	cin>>length;
	string letters;
	cin>>letters;
	string demo;
	lld friends;
	cin>>friends;
	string name;
	while(friends--)
    {
        cin>>name;
        demo = letters;
        lld maximum = 0;
        for(lld i=0; i<name.size(); i++)
        {
            for(lld j=0; j<demo.size(); j++)
            {
                if(demo[j]==name[i])
                {
                    demo[j] = '1';
                    maximum = max(maximum,j+1);
                    //cout<<"Maximum "<<maximum<<endl;
                    break;
                }
            }
        }
        cout<<maximum<<endl;
    }

	return 0;
}
