// This code is generated by ProgAst on Tue Mar 24 10:57:39 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1303B.cpp
// Problem Link: https://codeforces.com/problemset/problem/1303/B

// © Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	//fio;
	int test;
	cin>>test;
	while(test--)
    {
        long long int n, g, b, needG, totalG;
        cin>>n>>g>>b;
        if(n%2==0) needG = n/2;
        else needG = (n/2) + 1;
        totalG = (needG/g) * (g+b);
        if(needG%g>0) totalG = totalG + (needG%g);
        else totalG = totalG - b;
        cout<<max(n,totalG)<<endl;
    }

	return 0;
}
