// This code is generated by ProgAst on Sun Mar 22 23:30:35 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-659A.cpp
// Problem Link: https://codeforces.com/problemset/problem/659/A

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    //fio;
    int n, a, b;

    cin>>n>>a>>b;
    int ans = ((a-1+b) % n + n) % n + 1;
    cout<<ans<<endl;


    return 0;
}
