// This code is generated by ProgAst on Fri Apr 10 21:03:10 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1334B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	fio;
	int test;
	cin>>test;
	while(test--)
    {
        int person, margin, count = 0;
        cin>>person>>margin;
        long long int amount[person];
        for(int i=0; i<person; i++) cin>>amount[i];
        sort(amount,amount+person);
        long long int  sum = 0, welthy = 1;
        for(int i=person-1; i>=0; i--)
        {
            if((amount[i]+sum)/welthy>=margin)
            {
                sum = amount[i]+sum;
                welthy++;
            }
        }
        if(welthy>1) cout<<welthy-1<<endl;
        else cout<<0<<endl;
    }

	return 0;
}
// This code is generated by ProgAst on Fri Apr 10 23:41:20 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1334B.cpp
// Problem Link: 

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	fio;
	
	
	return 0;
}
