// This code is generated by ProgAst on Sun Mar 22 22:55:20 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-284A.cpp
// Problem Link: https://codeforces.com/problemset/problem/384/A

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	//fio;
	int n, ans;
	cin>>n;
	if(n%2==0) ans = (n * n) / 2;
	else ans = ((n * n) + 1) / 2;
	cout<<ans<<endl;
	for(int i=0; i<n; i++)
    {
        for(int j=0; j<n; j++)
        {
            if((i+j)%2==0) cout<<'C';
            else cout<<'.';
        }
        cout<<endl;
    }

	return 0;
}
