// This code is generated by ProgAst on Sun Mar 22 18:38:22 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1326A.cpp
// Problem Link: https://codeforces.com/contest/1326/problem/A

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    fio;

    int t, n;
    cin>>t;
    while(t--)
    {
        cin>>n;
        if(n==1)
            cout<<"-1"<<endl;
        else
        {
            cout<<2;
            for(int i=1; i<n; i++)
                cout<<3;
            cout<<endl;
        }
    }

    return 0;
}
