// This code is generated by ProgAst on Mon Apr 20 19:33:12 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1066C.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define FOR(start, end)           for(int i=start; i<end; i++)
#define FORR(start, end)          for(int j=start; j<end; j++)
#define RFOR(start, end)          for(int k=start-1; k>=end; k--)
#define MEM(Name, type)           memset(Name, type, sizeof(Name))
#define lld                       long long int
#define fio                       freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;

    map<int, int> desk;
    int q;
    char a;
    int b;
    int l=0, r=1;
    cin>>q;

    while(q--)
    {
        cin>>a>>b;
        if(a=='L')
            desk[b]=l--;
        else if(a=='R')
            desk[b]=r++;
        else
            cout<<min(desk[b]-l, r-desk[b])-1<<endl;
    }
    return 0;
}
