// This code is generated by ProgAst on Sat Apr 11 11:27:53 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1143B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);
int ans(int n);
int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    int n;
    cin>>n;
    cout<<ans(n);

    return 0;
}

int ans(int n)
{
    if(n==0)
        return 1;
    if(n<10)
        return n;
    return max(ans(n/10)*(n%10),ans(n/10-1)*9);
}
