// This code is generated by ProgAst on Sun Mar 29 15:40:31 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-265B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    fio;
    int N;
    cin >> N;
    int Ans=0,H=0;
    while(N--)
    {
        int X;
        cin >> X;
        Ans+=abs(H-X)+2;
        H=X;
    }
    cout << Ans-1 << endl;

    return 0;
}
