// This code is generated by ProgAst on Thu Apr 23 20:24:37 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1343B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define FOR(start, end)           for(int i=start; i<end; i++)
#define FORR(start, end)          for(int j=start; j<end; j++)
#define RFOR(start, end)          for(int k=start-1; k>=end; k--)
#define MEM(Name, type)           memset(Name, type, sizeof(Name))
#define lld                       long long int
#define fio                       freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	int test;
	cin>>test;
	while(test--)
    {
        int n;
        cin>>n;
        if(n%4!=0) cout<<"NO"<<endl;
        else{
            cout<<"YES"<<endl;
            int ans = 2;
            for(int i=1; i<=n/2; i++)
                cout<<ans<<" ",ans+=2;
            ans = 1;
            for(int i=1; i<n/2; i++)
                cout<<ans<<" ", ans+=2;

            cout<<ans+n/2<<endl;
        }
    }

	return 0;
}
