// This code is generated by ProgAst on Wed Apr 08 19:41:50 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-439A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    int Songs, Duration;
    cin>>Songs>>Duration;
    int Lengths[Songs], TotalLength = 0;
    for(int i=0; i<Songs; i++)
    {
        cin>>Lengths[i];
        TotalLength += Lengths[i];
    }
    if(TotalLength+(Songs-1)*10>Duration) cout<<-1;
    else{
        int Least = Duration - TotalLength-(Songs-1)*10;
        int Ans = (Songs-1)*2+Least/5;
        cout<<Ans;
    }

    return 0;
}
