// This code is generated by ProgAst on Sun Mar 29 21:23:24 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-733B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    int N, Left, Right, LeftSum = 0, RightSum = 0;
    cin>>N;
    int LLL[N], RRR[N];
    for(int i=0; i<N; i++)
    {
        cin>>Left>>Right;
        LLL[i] = Left;
        RRR[i] = Right;
        LeftSum += Left;
        RightSum += Right;
    }
    int InitialBeauty = abs(LeftSum-RightSum);
    int ProL, ProR, ProBeauty = 0, Max = 0, Index = -1;
    for(int i=0; i<N; i++)
    {
        ProL = LeftSum - LLL[i] + RRR[i];
        ProR = RightSum - RRR[i] + LLL[i];
        ProBeauty = abs(ProL-ProR);
        if(InitialBeauty<ProBeauty)
        {
            InitialBeauty = ProBeauty;
            Index = i;
        }
    }
    //cout<<"Max : "<<Max<<endl<<"Index : "<<Index<<endl;
    if(Index>-1) cout<<Index+1;
    else cout<<0;

    return 0;
}
