// This code is generated by ProgAst on Sat Mar 28 20:26:59 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1140A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	int Page, Max = 0, Count = 0;
	cin>>Page;
	int Mystery[Page];
	for(int i=0; i<Page; i++)
    {
        cin>>Mystery[i];
        Max = max(Mystery[i],Max);
        if(Max==i+1 && Mystery[i]>=Max) Count++;
    }
	cout<<Count;
	return 0;
}
