// This code is generated by ProgAst on Mon Apr 13 22:05:00 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1335D.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    fio;
    int test;
    cin>>test;
    while(test--)
    {
        int limit = 9;
        while(limit--)
        {
            string suduku;
            cin>>suduku;
            for(int i=0; i<9; i++)
            {
                if(suduku[i]=='3') cout<<2;
                else cout<<suduku[i];
            }
            cout<<endl;
        }


    }

    return 0;
}
