// This code is generated by ProgAst on Tue Apr 07 22:56:05 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-479A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	int A, B, C;
	cin>>A>>B>>C;
	int max1 = max((A+B)*C, A*B*C);
	int max2 = max(A*(B+C), A*B+C);
	int max3 = max(A+B+C, A+B*C);
	int Max = max(max1,max(max2,max3));
	cout<<Max;
	return 0;
}
