// This code is generated by ProgAst on Fri Mar 27 23:09:56 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-887A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    string Binary;
    cin>>Binary;
    int count0 = 0, count1 = 0;
    for(int i=0; i<Binary.size(); i++)
    {
        if(Binary[i]=='1')
        {
            for(int j=i; j<Binary.size(); j++)
            {
                if(Binary[j]=='0')
                    count0++;
                else
                    count1++;
            }
            break;
        }
    }
    if(count1>=1 && count0>5)
        cout<<"yes";
    else
        cout<<"no";

    return 0;
}
