// This code is generated by ProgAst on Tue Mar 24 12:16:01 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-534B.cpp
// Problem Link:

// © Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	//fio;
	int v1, v2, t, d;
    long long int ans = 0;
    cin >>v1>>v2>>t>>d;
    for(int i=1; i<=t; i++)
        {
        ans += min(v1 + (i-1)*d, v2 + (t-i)*d);
    }
    cout << ans << endl;

	return 0;
}
