// This code is generated by ProgAst on Tue Apr 07 21:48:11 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-118A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    string String;
    char C;
    cin>>String;
    for(int i=0; i<String.size(); i++)
    {
        C=tolower(String[i]);
        if(C!='a' && C!='e' && C!='i' && C!='o' && C!='u' && C!='y')
        {
            cout<<"."<<C;
        }
    }


    return 0;
}
