// This code is generated by ProgAst on Mon Mar 23 19:38:34 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1175A.cpp
// Problem Link: https://codeforces.com/problemset/problem/1175/A

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	//fio;
    int t;
    cin>>t;
    while(t--)
    {
        long long int n, k, ans = 0;
        cin>>n>>k;
        while(n!=0)
        {
            ans = ans + (n%k) + 1;
            n = n / k;
        }
        cout<<ans-1<<endl;
    }

	return 0;
}
