// This code is generated by ProgAst on Mon Mar 30 20:56:03 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-37A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	int N, X, Max = 0;
	set<int>Bers;
	cin>>N;
	int Index[5000] = {0};
	for(int i=0; i<N; i++)
    {
        cin>>X;
        Bers.insert(X);
        Index[X]++;
        Max = max(Max, Index[X]);
    }
    cout<<Max<<" "<<Bers.size();
	return 0;
}
