// This code is generated by ProgAst on Fri Mar 27 19:25:00 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-688B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	string Position;
	cin>>Position;
	cout<<Position;
	for(int i=Position.size()-1; i>=0; i--) cout<<Position[i];

	return 0;
}
