// This code is generated by ProgAst on Sun Mar 29 20:42:43 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-519A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    int White = 0, Black = 0;
    string Board[8];
    for(int i=0; i<8; i++)
        cin>>Board[i];
    for(int i=0; i<8; i++)
    {
        for(int j=0; j<8; j++)
        {
            if(Board[i][j]=='Q')
                White += 9;
            else if(Board[i][j]=='q')
                Black += 9;
            else if(Board[i][j]=='R')
                White += 5;
            else if(Board[i][j]=='r')
                Black += 5;
            else if(Board[i][j]=='B' || Board[i][j]=='N')
                White += 3;
            else if(Board[i][j]=='b' || Board[i][j]=='n')
                Black += 3;
            else if(Board[i][j]=='P')
                White += 1;
            else if(Board[i][j]=='p')
                Black += 1;
        }
    }
    //cout<<"White : "<<White<<endl;
    //cout<<"Black : "<<Black<<endl;
    if(White>Black)
        cout<<"White";
    else if(Black>White)
        cout<<"Black";
    else
        cout<<"Draw";

    return 0;
}
