// This code is generated by ProgAst on Sat Mar 28 11:56:39 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1257A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	fio;
	int Test, N, X, A, B;
	cin>>Test;
	while(Test--)
    {
        cin>>N>>X>>A>>B;
        if(abs(A-B)+X>=N) cout<<N-1<<endl;
        else cout<<abs(A-B)+X<<endl;
    }

	return 0;
}
