// This code is generated by ProgAst on Sun Apr 19 21:45:49 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-747B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define FOR(start, end)           for(int i=start; i<end; i++)
#define FORR(start, end)          for(int j=start; j<end; j++)
#define RFOR(start, end)          for(int k=start-1; k>=end; k--)
#define MEM(Name, type)           memset(Name, type, sizeof(Name))
#define lld                       long long int
#define fio                       freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	int len;
	string genom;
	cin>>len>>genom;
	if(len%4!=0)
    {
        cout<<"==="<<endl;
        return 0;
    }
    else
    {
        int A = 0, G = 0, C = 0, T = 0;
        FOR(0,len)
        {
            if(genom[i]=='A') A++;
            else if(genom[i]=='G') G++;
            else if(genom[i]=='C') C++;
            else if(genom[i]=='T') T++;
        }
        if(A>len/4 || G>len/4 || C>len/4 || T>len/4)
        {
            cout<<"==="<<endl;
            return 0;
        }
        int i;
        for(i=0;len/4!=A;i++)
        {
            if(genom[i]=='?')
            {
                genom[i] = 'A';
                A++;
            }
        }
        for(i;len/4!=G;i++)
        {
            if(genom[i]=='?')
            {
                genom[i] = 'G';
                G++;
            }
        }
        for(i;len/4!=C;i++)
        {
            if(genom[i]=='?')
            {
                genom[i] = 'C';
                C++;
            }
        }
        for(i;len/4!=T;i++)
        {
            if(genom[i]=='?')
            {
                genom[i] = 'T';
                T++;
            }
        }
        cout<<genom<<endl;
    }

	return 0;
}
