// This code is generated by ProgAst on Fri Mar 27 11:36:58 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1301A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	//cin.tie(null);
	fio;
	int TestCase;
	cin>>TestCase;
	while(TestCase--)
    {
        string First, Second, Third;
        cin>>First>>Second>>Third;
        bool Flag = true;
        for(int i=0; i<First.size(); i++)
        {
            //cout<<"IN The LOOP"<<endl;
            if(First[i]!=Third[i] && Second[i]!=Third[i]){
                Flag = false;
                break;
            }
            //cout<<"Flag "<<Flag<<endl;
        }
        if(Flag) cout<<"YES"<<endl;
        else cout<<"NO"<<endl;
    }

	return 0;
}
