// This code is generated by ProgAst on Mon Mar 30 19:33:37 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-118B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

void Printer(int N,int Space)
{
    for(int i=0; i<2*Space; i++) cout<<" ";
    for(int i=0; i<N; i++) cout<<i<<" ";
    cout<<N;
    N--;
    for(int i=N; i>=0; i--) cout<<" "<<i;
    cout<<endl;
}
int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    int N, Number, Increase, Decrease;
    cin>>N;
    int M = N-1, s=N;
    for(int i=0; i<2*N+1; i++)
    {
        if(i<N) Printer(i,s);
        else if(i==N) Printer(i,0);
        else {
            Printer(M,i-N);
            M--;
        }
        s--;
    }

    return 0;
}
