// This code is generated by ProgAst on Tue Mar 24 22:08:07 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1234A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    fio;
    long long int t;
    cin>>t;
    while(t--)
    {
        long long int n,a,sum=0;
        cin>>n;
        for(long long int i=0; i<n; i++)
        {
            cin>>a;
            sum+=a;
        }
        long long int ans=ceil((sum*1.0)/n);
        cout<<ans<<endl;
    }

    return 0;
}
