// This code is generated by ProgAst on Sun Apr 12 19:40:20 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-25A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);
void FIO()
{
#ifndef _offline
    freopen("input.txt", "r", stdin);
    //freopen("output.txt", "w", stdout);
#endif
}
int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //FIO();

    cin>>n;
    for (i=0; i<n; i++)
    {
        cin>>a;
        if (a%2==0)
            b++,k=i+1;
        else
            c++,l=i+1;
    }
    if (b==1)
        cout<<k;
    else
        cout<<l;


    return 0;
}
