// This code is generated by ProgAst on Sun Apr 19 22:10:03 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1146B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define FOR(start, end)           for(int i=start; i<end; i++)
#define FORR(start, end)          for(int j=start; j<end; j++)
#define RFOR(start, end)          for(int k=start-1; k>=end; k--)
#define MEM(Name, type)           memset(Name, type, sizeof(Name))
#define lld                       long long int
#define fio                       freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    string t;
    cin>>t;
    vector<char>vec;
    for(int i=0; t[i]; i++)
    {
        if(t[i]!='a')
            vec.push_back(t[i]);
    }
    if(t[t.size()]=='a')
    {
        cout<<":(";
        return 0;
    }
    else if(vec.size()%2==1)
    {
        cout<<":(";
        return 0;
    }
    else
    {
        for(int i=0; i<vec.size()/2; i++)
        {
            if(vec[i]!=vec[vec.size()/2])
            {
                cout<<":(";
                return 0;
            }
        }
    }

    return 0;
}
