// This code is generated by ProgAst on Thu Apr 09 20:27:26 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-651A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	int first, second, count = 0;
	cin>>first>>second;
	while(first>0 && second>0)
    {
        if(first<=second)
        {
            first += 1;
            second -= 2;
        }
        else
        {
            first -= 2;
            second += 1;
        }
        if (first>=0 && second>=0) count++;
    }
	cout<<count;
	return 0;
}
