// This code is generated by ProgAst on Thu Apr 16 21:09:08 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1294B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define FOR(start, end)           for(int i=start; i<end; i++)
#define FORR(start, end)          for(int j=start; j<end; j++)
#define RFOR(start, end)          for(int k=start-1; k>=end; k--)
#define MEM(Name, type)           memset(Name, type, sizeof(Name))
#define lld                       long long int
#define fio                       freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    int t;
    cin >> t;

    for (int tt = 0; tt < t; tt++)
    {
        int n;
        cin >> n;
        vector<pair<int, int>> a(n);
        for (int i = 0; i < n; ++i)
        {
            cin >> a[i].first >> a[i].second;
        }
        sort(a.begin(), a.end());
        pair<int, int> cur = make_pair(0, 0);
        string ans;
        bool ok = true;
        for (int i = 0; i < n; ++i)
        {
            int r = a[i].first - cur.first;
            int u = a[i].second - cur.second;
            if (r < 0 || u < 0)
            {
                cout << "NO" << endl;
                ok = false;
                break;
            }
            ans += string(r, 'R');
            ans += string(u, 'U');
            cur = a[i];
        }

        if (ok)
            cout << "YES" << endl << ans << endl;
    }
    return 0;
}
