// This code is generated by ProgAst on Mon Mar 23 21:31:28 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1329A.cpp
// Problem Link: https://codeforces.com/contest/1327/problem/A

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	fio;
	
	
	return 0;
}
