// This code is generated by ProgAst on Mon Mar 23 18:57:04 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-584A.cpp
// Problem Link: https://codeforces.com/problemset/problem/584/A

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    //fio;
    int n, t;
    cin>>n>>t;
    if(t<10)
    {
        for(int i=1; i<=n; ++i)
            cout<<t;
    }
    else
    {
        if(n==1)
            cout<<-1;
        else
        {
            cout<<1;
            for(int i=1; i<=n-1; ++i)
                cout<<0;
        }
    }
    return 0;
}
