// This code is generated by ProgAst on Sun Mar 29 18:56:23 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-234B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	int Hours, ReadHours;
	cin>>Hours>>ReadHours;
	pair<int,int>Inputs[Hours];
	for(int i=0; i<Hours; i++){
        cin>>Inputs[i].first;
        Inputs[i].second = i+1;
	}
	sort(Inputs,Inputs+Hours);

    cout<<Inputs[Hours-ReadHours].first<<endl;
    for(int i=Hours-ReadHours; i<Hours; i++) cout<<Inputs[i].second<<" ";

	return 0;
}
