// This code is generated by ProgAst on Mon Apr 13 21:10:43 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1335C.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	fio;
	int test;
	cin>>test;
	while(test--)
    {
        long long int n, x, same = 0, diff = 0;
        cin>>n;
        long long int mark[n+1] = {0};
        for(int i=1; i<=n; i++)
        {
            cin>>x;
            mark[x]++;
        }
        for(int i=1; i<=n; i++)
        {
            same = max(same,mark[i]);
            if(mark[i]>0) diff++;
        }
        if(same==diff-1) cout<<diff-1<<endl;
        else if(same<diff-1) cout<<same<<endl;
        else cout<<min(same-1,diff)<<endl;
    }

	return 0;
}
