// This code is generated by ProgAst on Mon Apr 20 18:43:01 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1066A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define FOR(start, end)           for(int i=start; i<end; i++)
#define FORR(start, end)          for(int j=start; j<end; j++)
#define RFOR(start, end)          for(int k=start-1; k>=end; k--)
#define MEM(Name, type)           memset(Name, type, sizeof(Name))
#define lld                       long long int
#define fio                       freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	fio;
	int test;
	cin>>test;
	while(test--)
    {
        lld L, v, l, r;
        cin>>L>>v>>l>>r;
        lld before = (l-1)/v;
        lld during = r/v;
        lld after = L/v;
        //for(int i=l; i<=r; i++)
        //{
        //    if(i%v==0) counter--;
        //}
        cout<<after-during+before<<endl;
    }

	return 0;
}
