// This code is generated by ProgAst on Thu Mar 26 20:38:04 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1328A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    //cin.tie(null);
    fio;
    int Test;
    cin>>Test;
    while(Test--)
    {
        long long int Number, Divisor;
        cin>>Number>>Divisor;
        if(Number%Divisor==0)
            cout<<0<<endl;
        else
        {
            long long int Ans = Divisor-(Number%Divisor);
            cout<<Ans<<endl;
        }

    }

    return 0;
}
