// This code is generated by ProgAst on Sun Mar 29 14:12:30 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1141B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	int N, Count = 0, Max = 0;
	cin>>N;
	int Marker[N];
	for(int i=0; i<N; i++)
    {
        cin>>Marker[i];
        if(Marker[i]==1) Count++;
        else{
            Max = max(Count, Max);
            Count = 0;
        }
    }
    for(int i=0; i<N; i++)
    {
        if(Marker[i]==1) Count++;
        else{
            Max = max(Max, Count);
            break;
        }
    }
	cout<<Max;
	return 0;
}
