// This code is generated by ProgAst on Sun Mar 22 23:06:54 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-766B.cpp
// Problem Link: https://codeforces.com/problemset/problem/766/B

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    //fio;
    int n, sum;
    cin>>n;
    int arr[n];
    for(int i=0; i<n; i++)
        cin>>arr[i];
    sort(arr,arr+n);
    for (int i=1; i<n-1; i++)
    {
        if (arr[i-1]+arr[i]>arr[i+1])
        {
            cout << "YES";
            return 0;
        }
    }
    cout<<"NO";
    return 0;
}
