// This code is generated by ProgAst on Sun Mar 29 14:41:10 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-680B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    int City, Pos, Ans = 0;
    cin>>City>>Pos;
    int Marker[City];
    for(int i=0; i<City; i++)
        cin>>Marker[i];
    if(Marker[Pos-1]==1)
        Ans++;
    for(int i=1; i<=City; i++)
    {
        if(Pos-1-i>=0 && Pos-1+i<City)
        {
            if(Marker[Pos-1-i]==1 && Marker[Pos-1+i]==1)
                Ans += 2;
        }
        else
            break;
    }
    int Left = Pos-1;
    int Right = City-Pos;
    if(Left>Right)
    {
        for(int i=0; i<Left-Right; i++)
        {
            if(Marker[i]==1)
                Ans++;
        }
    }
    else if(Right>Left)
    {
        for(int i=Pos+Left; i<City; i++)
        {
            if(Marker[i]==1)
                Ans++;
        }
    }
    cout<<Ans;

    return 0;
}
