// This code is generated by ProgAst on Sat Mar 28 20:41:59 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1088A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	int X;
	cin>>X;
	if(X==1) cout<<-1;
	else cout<<X-X%2<<" "<<2;

	return 0;
}
