// This code is generated by ProgAst on Fri Apr 10 00:07:30 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-219A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	int k, mark[256] = {0};
	string str;
	cin>>k>>str;
	for(int i=0; i<str.size(); i++) mark[str[i]]++;
	for(int i=97; i<123; i++)
    {
        if(mark[i]%k!=0)
        {
            cout<<-1;
            return 0;
        }
    }
    while(k>0)
    {
        for(int i=97; i<123; i++)
        {
            for(int j=0; j<mark[i]/k; j++)
            {
                printf("%c",i);
            }
            mark[i] -= mark[i]/k;
        }
        k--;
    }

	return 0;
}
