// This code is generated by ProgAst on Fri Apr 10 20:24:43 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-492B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	int lanthan,street_length;
    int lb,rb;
    cin>>lanthan>>street_length;
    int a[lanthan],dia=0;
    float max_distance=0;
    for(int i=0;i<lanthan;i++)
        cin>>a[i];
        sort(a,a+lanthan);
        for(int i=1;i<lanthan;i++)
        {
            dia=a[i]-a[i-1];
            if(float(dia)>max_distance)
                max_distance=float(dia);

        }
        max_distance=max_distance/2;
        lb=a[0],rb=street_length-a[lanthan-1];
        if(float(lb)>max_distance)
            max_distance=float(lb);
        if(float(rb)>max_distance)
            max_distance=float(rb);
        printf("%.10f",max_distance);

	return 0;
}
