// This code is generated by ProgAst on Fri Mar 27 19:30:43 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-34B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    int N, M, Ans = 0, count = 0;
    cin>>N>>M;
    int Tvsets[N];
    for(int i=0; i<N; i++)
    {
        cin>>Tvsets[i];
    }
    sort(Tvsets, Tvsets+N);
    for(int i=0; i<M; i++)
    {
        if(Tvsets[i]<0)
            Ans = Ans + abs(Tvsets[i]);
        else
            break;
    }
    cout<<Ans;
    return 0;
}
