// This code is generated by ProgAst on Sun Mar 29 23:12:30 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-706B.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	fio;
	int Shop;
	cin>>Shop;
	int Price[Shop];
	for(int i=0; i<Shop; i++) cin>>Price[i];
	int Day, Count = 0;
	cin>>Day;
	sort(Price,Price+Shop);
	long long int Coin;
	for(int i=0; i<Day; i++)
	{
        cin>>Coin;
        int Ans = upper_bound(Price,Price+Shop,Coin)-Price;
        cout<<Ans<<endl;
	}
	return 0;
}
