// This code is generated by ProgAst on Wed Apr 08 19:18:43 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-149A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	//fio;
	int Length, Month[12], Ans = 0, Sum = 0;
	cin>>Length;
	for(int i=0; i<12; i++) cin>>Month[i];
	if(Length==0) cout<<0;
	else{
        sort(Month, Month+12);
        for(int i=11; i>=0; i--)
        {
            Sum += Month[i];
            Ans++;
            if(Sum>=Length) break;
        }
        if(Sum<Length) cout<<-1;
        else cout<<Ans;
	}

	return 0;
}
