// This code is generated by ProgAst on Tue Apr 07 23:24:17 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-500A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    int N, T;
    cin>>N>>T;
    int A[N+2];
    for (int i = 1; i < N; i++)
    {
        cin>>A[i];
    }
    //A[N] = 1;
    for(int i=1; i< T;)
    {
        i += A[i];
        if(i==T)
        {
            cout<<"YES";
            return 0;
        }
    }

    cout<<"NO";


    return 0;
}
