// This code is generated by ProgAst on Sat Mar 28 11:45:39 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1196A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	fio;
	long long int Test, A, B, C;
	cin>>Test;
	while(Test--)
    {
        long long int Total = 0;
        cin>>A>>B>>C;
        Total = A+B+C;
        cout<<Total/2<<endl;
    }
	return 0;
}
