// This code is generated by ProgAst on Thu Apr 23 20:53:54 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1341A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define FOR(start, end)           for(int i=start; i<end; i++)
#define FORJ(start, end)          for(int j=start; j<end; j++)
#define FORK(start, end)          for(int k=start-1; k>=end; k--)
#define MEM(Name, type)           memset(Name, type, sizeof(Name))
#define lld                       long long int
#define fio                       freopen("input.txt","r",stdin);

int main()
{
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	fio;
	int test;
	cin>>test;
	while(test--)
    {
        int n, a, b, c, d;
        cin>>n>>a>>b>>c>>d;
        int t1 = a-b, t2 = a+b, z1 = c-d, z2 = c+d;
        if(n*t1>z2 || n*t2<z1) cout<<"NO"<<endl;
        else cout<<"YES"<<endl;
    }

	return 0;
}
