// This code is generated by ProgAst on Sun Mar 22 18:57:05 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-1326B.cpp
// Problem Link: https://codeforces.com/contest/1326/problem/B

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
	fio;
    int n;
    cin>>n;
    int input_array[n];
    int result_array[n];
    for(int i=0; i<n; i++)
    {
        cin>>input_array[i];
    }
    result_array[0] = input_array[0];
    int max = result_array[0];
    for(int i=1; i<n; i++)
    {
        if(max<result_array[i-1]) max = result_array[i-1];
        result_array[i] = max + input_array[i];
    }
    for(int i=0; i<n; i++)
    {
        cout<<result_array[i]<<" ";
    }
	return 0;
}
