// This code is generated by ProgAst on Thu Apr 09 22:07:03 BDT 2020
// ProgAst Developer : Suvash Kumar Sumon, suvashkumar.naogaon@gmail.com
// File Name: Codeforces-675A.cpp
// Problem Link:

// Author : Suvash Kumar Sumon

#include<bits/stdc++.h>
using namespace std;

#define fio freopen("input.txt","r",stdin);

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    //fio;
    long long int a, b, c;
    cin>>a>>b>>c;
    if (c == 0)
    {
        if (a == b)
            cout << "YES";
        else
            cout << "NO";
    }
    else
    {
        if ((b-a)%c==0 && (b-a)/c>=0)
            cout<<"YES";
        else
            cout<<"NO";
    }
    return 0;
}
